### ISSUE TITLE
问卷调查

### ISSUE THREAD

**Issue by hyfree** [taozhang-tt/leanote-sync#1]
1. 你本地最喜欢的编辑器是什么
2. 你正在使用的本地markdown编辑器有哪些
2. 你常用的操作系统有哪些

**Comment by taozhang-tt** [comment]
1，vim
2，vim，vscode
3，macOS，centos

**Comment by hyfree** [comment]
图片直接放在文件夹里面就可以了吗

还是需要额外处理
你写的同步软件

**Comment by taozhang-tt** [comment]
图片的话我一直是放在阿里云图床的。
我平常的使用习惯是快捷截屏，图片会在剪切板，然后自己写了个小工具会自动把剪切板的图片上传到阿里云图床，并把图片的地址放入剪切板，所以我直接在markdown文件里插入图片链接就好了。

这个同步只是简单地同步本地的笔记目录到服务器上，也就是说没有这个服务器，我直接在本地写笔记也是ok的

**Comment by hyfree** [comment]
剪贴工具支持Linux，Mac OS和Windows吗

**Comment by taozhang-tt** [comment]
我写的时候是支持的，不过我只有mac，所以win下没有测试过，你可以试试看
https://github.com/taozhang-tt/md-pic

**Comment by hyfree** [comment]
ε(*･ω･)_/ﾟ:･☆
写个双向同步的怎么样

**Comment by hyfree** [comment]
可不可以给项目添加一个开源协议
我想抄一下你的作业
这个项目和复制剪贴板的项目
md-pic和leanote-sync

**Comment by taozhang-tt** [comment]
好的，没问题，在上班，晚会我搞一下

**Comment by taozhang-tt** [comment]
> 

加好了

**Comment by hyfree** [comment]
根据Apache-2.0 License协议需要，已经引用你的代码，请知悉。
开源地址：https://github.com/morenote/morenote-sync-cli
