### ISSUE TITLE
关于 update字段

### ISSUE THREAD

**Issue by wg1026688210** [taozhang-tt/leanote-sync#2]
请教下作者  update 字段是什么意思

**Comment by wg1026688210** [comment]
修改未生效
![image](https://user-images.githubusercontent.com/14267759/148670680-e02b8bc4-a974-40e3-b2b8-e460678fa1d3.png)
![image](https://user-images.githubusercontent.com/14267759/148670689-5096bac6-8eb5-4dfb-875d-677fc56323c1.png)

**Comment by wg1026688210** [comment]
现象我可能描述得不太清楚  我在本地修改了文件内容 ，将'目前'改成. '现在' ,使用脚本未同步成功
updated =0,1都试过

**Comment by taozhang-tt** [comment]
我试了下，好像是updateNote接口有点问题，我今天检查一下

**Comment by taozhang-tt** [comment]
已修复

**Comment by wg1026688210** [comment]
太感谢了,再请教个问题,之前安装过咱们脚本,如果想升级下脚本需要怎么做，有没有相关wiki可以参考下

**Comment by taozhang-tt** [comment]
拉取一下最新代码，重新执行一下make命令就可以了，就是按原来的安装流程再走一遍

**Comment by wg1026688210** [comment]
刚才拉下代码测了一下，没问题了
